package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrAgencias generated by hbm2java
 */
@Entity
@Table(name="pr_agencias"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="alias"), @UniqueConstraint(columnNames="agencia")} 
)
public class PrAgencias  implements java.io.Serializable {


     private int idagencia;
     private String alias;
     private String agencia;
     private String cuit;
     private Double latitud;
     private Double longitud;
     private String domicilio;
     private Set timeships = new HashSet(0);

    public PrAgencias() {
    }

    public PrAgencias( String alias, String agencia, String cuit, String domicilio) {
        this.alias = alias;
        this.agencia = agencia;
        this.cuit = cuit;
        this.domicilio=domicilio;
    }

    
    public PrAgencias(int idagencia, String alias, String agencia, String cuit, String domicilio) {
        this.idagencia = idagencia;
        this.alias = alias;
        this.agencia = agencia;
        this.cuit = cuit;
        this.domicilio=domicilio;
    }
    
    public PrAgencias(int idagencia, String alias, String agencia, String cuit, Double latitud, Double longitud, String domicilio, Set timeships) {
       this.idagencia = idagencia;
       this.alias = alias;
       this.agencia = agencia;
       this.cuit = cuit;
       this.latitud = latitud;
       this.longitud = longitud;
       this.domicilio = domicilio;
       this.timeships = timeships;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.pr_agencias_idagencia_seq")
    @Column(name="idagencia", unique=true, nullable=false, insertable = false)
    public int getIdagencia() {
        return this.idagencia;
    }
    
    public void setIdagencia(int idagencia) {
        this.idagencia = idagencia;
    }

    
    @Column(name="alias", unique=true, nullable=false, length=10)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    
    @Column(name="agencia", unique=true, nullable=false, length=100)
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }

    
    @Column(name="cuit", nullable=false, length=20)
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }

    
    @Column(name="latitud", precision=17, scale=17)
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", precision=17, scale=17)
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="domicilio", length=100)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prAgencias")
    public Set getTimeships() {
        return this.timeships;
    }
    
    public void setTimeships(Set timeships) {
        this.timeships = timeships;
    }




}


