package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrBuques generated by hbm2java
 */
@Entity
@Table(name="pr_buques"
    ,schema="public"
)
public class PrBuques  implements java.io.Serializable {


     private int idbuque;
     private String imo;
     private String nombre;
     private String flag;
     private BigDecimal grt;
     private BigDecimal eslora;
     private BigDecimal manga;
     private BigDecimal puntal;
     private BigDecimal coef;
     private BigDecimal grtfac;
     private BigDecimal coeffac;
     private Set timeships = new HashSet(0);

    public PrBuques() {
    }

	
    public PrBuques(int idbuque, String imo, String nombre, String flag) {
        this.idbuque = idbuque;
        this.imo = imo;
        this.nombre = nombre;
        this.flag = flag;
    }
    public PrBuques(int idbuque, String imo, String nombre, String flag, BigDecimal grt, BigDecimal eslora, BigDecimal manga, BigDecimal puntal, BigDecimal coef, BigDecimal grtfac, BigDecimal coeffac, Set timeships) {
       this.idbuque = idbuque;
       this.imo = imo;
       this.nombre = nombre;
       this.flag = flag;
       this.grt = grt;
       this.eslora = eslora;
       this.manga = manga;
       this.puntal = puntal;
       this.coef = coef;
       this.grtfac = grtfac;
       this.coeffac = coeffac;
       this.timeships = timeships;
    }
   
       public PrBuques( String imo, String nombre, String flag, BigDecimal grt, BigDecimal eslora, BigDecimal manga, BigDecimal puntal, BigDecimal coef, BigDecimal grtfac, BigDecimal coeffac) {
       this.idbuque = idbuque;
       this.imo = imo;
       this.nombre = nombre;
       this.flag = flag;
       this.grt = grt;
       this.eslora = eslora;
       this.manga = manga;
       this.puntal = puntal;
       this.coef = coef;
       this.grtfac = grtfac;
       this.coeffac = coeffac;
       this.timeships = timeships;
    }
   
    
    
     @Id 

     @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.pr_buques_idbuque_seq")
     @Column(name="idbuque", unique=true, nullable=false, insertable = false)
    public int getIdbuque() {
        return this.idbuque;
    }
    
    public void setIdbuque(int idbuque) {
        this.idbuque = idbuque;
    }

    
    @Column(name="imo", nullable=false, length=10)
    public String getImo() {
        return this.imo;
    }
    
    public void setImo(String imo) {
        this.imo = imo;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="flag", nullable=false, length=10)
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    
    @Column(name="grt", precision=18)
    public BigDecimal getGrt() {
        return this.grt;
    }
    
    public void setGrt(BigDecimal grt) {
        this.grt = grt;
    }

    
    @Column(name="eslora", precision=18)
    public BigDecimal getEslora() {
        return this.eslora;
    }
    
    public void setEslora(BigDecimal eslora) {
        this.eslora = eslora;
    }

    
    @Column(name="manga", precision=18)
    public BigDecimal getManga() {
        return this.manga;
    }
    
    public void setManga(BigDecimal manga) {
        this.manga = manga;
    }

    
    @Column(name="puntal", precision=18)
    public BigDecimal getPuntal() {
        return this.puntal;
    }
    
    public void setPuntal(BigDecimal puntal) {
        this.puntal = puntal;
    }

    
    @Column(name="coef", precision=18)
    public BigDecimal getCoef() {
        return this.coef;
    }
    
    public void setCoef(BigDecimal coef) {
        this.coef = coef;
    }

    
    @Column(name="grtfac", precision=18)
    public BigDecimal getGrtfac() {
        return this.grtfac;
    }
    
    public void setGrtfac(BigDecimal grtfac) {
        this.grtfac = grtfac;
    }

    
    @Column(name="coeffac", precision=18)
    public BigDecimal getCoeffac() {
        return this.coeffac;
    }
    
    public void setCoeffac(BigDecimal coeffac) {
        this.coeffac = coeffac;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prBuques")
    public Set getTimeships() {
        return this.timeships;
    }
    
    public void setTimeships(Set timeships) {
        this.timeships = timeships;
    }




}


