package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrEmpresasCoordinacion generated by hbm2java
 */
@Entity
@Table(name="pr_empresas_coordinacion"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="empresa") 
)
public class PrEmpresasCoordinacion  implements java.io.Serializable {


     private int idempresacoordinacion;
     private String empresa;
     private String cuit;
     private String domicilio;
     private Set timeships = new HashSet(0);

    public PrEmpresasCoordinacion() {
    }

	
    public PrEmpresasCoordinacion(int idempresacoordinacion, String empresa, String cuit) {
        this.idempresacoordinacion = idempresacoordinacion;
        this.empresa = empresa;
        this.cuit = cuit;
    }
    
    public PrEmpresasCoordinacion( String empresa, String cuit, String domicilio) {
       this.empresa = empresa;
       this.cuit = cuit;
       this.domicilio = domicilio;
       
    }
    
    public PrEmpresasCoordinacion(int idempresacoordinacion, String empresa, String cuit, String domicilio, Set timeships) {
       this.idempresacoordinacion = idempresacoordinacion;
       this.empresa = empresa;
       this.cuit = cuit;
       this.domicilio = domicilio;
       this.timeships = timeships;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.pr_empresas_coordinacion_idempresacoordinacion_seq")
    @Column(name="idempresacoordinacion", unique=true, nullable=false, insertable = false)
    public int getIdempresacoordinacion() {
        return this.idempresacoordinacion;
    }
    
    public void setIdempresacoordinacion(int idempresacoordinacion) {
        this.idempresacoordinacion = idempresacoordinacion;
    }

    
    @Column(name="empresa", unique=true, nullable=false, length=100)
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="cuit", nullable=false, length=20)
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }

    
    @Column(name="domicilio", length=100)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prEmpresasCoordinacion")
    public Set getTimeships() {
        return this.timeships;
    }
    
    public void setTimeships(Set timeships) {
        this.timeships = timeships;
    }




}


