package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrMuelles generated by hbm2java
 */
@Entity
@Table(name="pr_muelles"
    ,schema="public"
)
public class PrMuelles  implements java.io.Serializable {


     private int idmuelle;
     private PrPuertos prPuertos;
     private String muelle;
     private Long kilometro;
     private String emax;
     private Long rv;
     private String estructura;
     private BigDecimal det;
     private Double latitud;
     private Double longitud;
     private Set timeships = new HashSet(0);
     private int idpuerto;



    public PrMuelles() {
    }

	
    public PrMuelles(int idmuelle, PrPuertos prPuertos, String muelle) {
        this.idmuelle = idmuelle;
        this.prPuertos = prPuertos;
        this.muelle = muelle;
    }
    public PrMuelles(int idmuelle, PrPuertos prPuertos, String muelle, Long kilometro, String emax, Long rv, String estructura, BigDecimal det, Double latitud, Double longitud, Set timeships) {
       this.idmuelle = idmuelle;
       this.prPuertos = prPuertos;
       this.muelle = muelle;
       this.kilometro = kilometro;
       this.emax = emax;
       this.rv = rv;
       this.estructura = estructura;
       this.det = det;
       this.latitud = latitud;
       this.longitud = longitud;
       this.timeships = timeships;
    }

     public PrMuelles(  String muelle, Long kilometro, String emax, Long rv, String estructura, BigDecimal det, Double latitud, Double longitud, PrPuertos prpuertos) {
      
       this.muelle = muelle;
       this.kilometro = kilometro;
       this.emax = emax;
       this.rv = rv;
       this.estructura = estructura;
       this.det = det;
       this.latitud = latitud;
       this.longitud = longitud;
       this.prPuertos=prpuertos;
       
       
    }

    
    
    
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.pr_muelles_idmuelle_seq")
    @Column(name="idmuelle", unique=true, nullable=false, insertable= false)
    public int getIdmuelle() {
        return this.idmuelle;
    }
    
    public void setIdmuelle(int idmuelle) {
        this.idmuelle = idmuelle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpuerto", nullable=false)
    public PrPuertos getPrPuertos() {
        return this.prPuertos;
    }
    
    public void setPrPuertos(PrPuertos prPuertos) {
        this.prPuertos = prPuertos;
    }

    
    @Column(name="muelle", nullable=false, length=50)
    public String getMuelle() {
        return this.muelle;
    }
    
    public void setMuelle(String muelle) {
        this.muelle = muelle;
    }

    
    @Column(name="kilometro", precision=18, scale=0)
    public Long getKilometro() {
        return this.kilometro;
    }
    
    public void setKilometro(Long kilometro) {
        this.kilometro = kilometro;
    }

    
    @Column(name="emax", length=30)
    public String getEmax() {
        return this.emax;
    }
    
    public void setEmax(String emax) {
        this.emax = emax;
    }

    
    @Column(name="rv", precision=18, scale=0)
    public Long getRv() {
        return this.rv;
    }
    
    public void setRv(Long rv) {
        this.rv = rv;
    }

    
    @Column(name="estructura", length=200)
    public String getEstructura() {
        return this.estructura;
    }
    
    public void setEstructura(String estructura) {
        this.estructura = estructura;
    }

    
    @Column(name="det", precision=18, scale=1)
    public BigDecimal getDet() {
        return this.det;
    }
    
    public void setDet(BigDecimal det) {
        this.det = det;
    }

    
    @Column(name="latitud", precision=17, scale=17)
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", precision=17, scale=17)
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prMuelles")
    public Set getTimeships() {
        return this.timeships;
    }
    
    public void setTimeships(Set timeships) {
        this.timeships = timeships;
    }

    public void setIdpuerto(int idpuerto) {
        this.idpuerto = idpuerto;
    }

    public int getIdpuerto() {
        return idpuerto;
    }


}


