package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PrPracticos generated by hbm2java
 */
@Entity
@Table(name="pr_practicos"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="habilitacion") 
)
public class PrPracticos  implements java.io.Serializable {


     private int idpractico;
     private String practico;
     private String habilitacion;
     private String telefono;
     private String celular;
     private String otroTelefono;
     private String direccion;
     private Date FRevisacionMedica;
     private Date FVencChalecoSalv;
     private Set timeships = new HashSet(0);

    public PrPracticos() {
    }

	
    public PrPracticos(int idpractico, String practico) {
        this.idpractico = idpractico;
        this.practico = practico;
    }
    public PrPracticos(int idpractico, String practico, String habilitacion, String telefono, String celular, String otroTelefono, String direccion, Date FRevisacionMedica, Date FVencChalecoSalv, Set timeships) {
       this.idpractico = idpractico;
       this.practico = practico;
       this.habilitacion = habilitacion;
       this.telefono = telefono;
       this.celular = celular;
       this.otroTelefono = otroTelefono;
       this.direccion = direccion;
       this.FRevisacionMedica = FRevisacionMedica;
       this.FVencChalecoSalv = FVencChalecoSalv;
       this.timeships = timeships;
    }

       public PrPracticos( String practico, String habilitacion, String telefono, String celular, String otroTelefono, String direccion, Date FRevisacionMedica, Date FVencChalecoSalv) {
       this.practico = practico;
       this.habilitacion = habilitacion;
       this.telefono = telefono;
       this.celular = celular;
       this.otroTelefono = otroTelefono;
       this.direccion = direccion;
       this.FRevisacionMedica = FRevisacionMedica;
       this.FVencChalecoSalv = FVencChalecoSalv;
    }
    
    
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.pr_practicos_idpractico_seq")
    @Column(name="idpractico", unique=true, nullable=false, insertable = false)
    public int getIdpractico() {
        return this.idpractico;
    }
    
    public void setIdpractico(int idpractico) {
        this.idpractico = idpractico;
    }

    
    @Column(name="practico", nullable=false, length=50)
    public String getPractico() {
        return this.practico;
    }
    
    public void setPractico(String practico) {
        this.practico = practico;
    }

    
    @Column(name="habilitacion", unique=true, length=10)
    public String getHabilitacion() {
        return this.habilitacion;
    }
    
    public void setHabilitacion(String habilitacion) {
        this.habilitacion = habilitacion;
    }

    
    @Column(name="telefono", length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="celular", length=30)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="otro_telefono", length=30)
    public String getOtroTelefono() {
        return this.otroTelefono;
    }
    
    public void setOtroTelefono(String otroTelefono) {
        this.otroTelefono = otroTelefono;
    }

    
    @Column(name="direccion", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_revisacion_medica", length=13)
    public Date getFRevisacionMedica() {
        return this.FRevisacionMedica;
    }
    
    public void setFRevisacionMedica(Date FRevisacionMedica) {
        this.FRevisacionMedica = FRevisacionMedica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_venc_chaleco_salv", length=13)
    public Date getFVencChalecoSalv() {
        return this.FVencChalecoSalv;
    }
    
    public void setFVencChalecoSalv(Date FVencChalecoSalv) {
        this.FVencChalecoSalv = FVencChalecoSalv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prPracticos")
    public Set getTimeships() {
        return this.timeships;
    }
    
    public void setTimeships(Set timeships) {
        this.timeships = timeships;
    }




}


