package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrPuertos generated by hbm2java
 */
@Entity
@Table(name="pr_puertos"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="puerto") 
)
public class PrPuertos  implements java.io.Serializable {


     private int idpuerto;
     private String puerto;
     private BigDecimal adicional;
     private BigDecimal bonificacion;
     private Integer interno;
     private Double latitud;
     private Double longitud;
     private String domicilio;
     private Set prMuelleses = new HashSet(0);
     private Set timeshipsForIdpuertoorigen = new HashSet(0);
     private Set timeshipsForIdpuertodestino = new HashSet(0);

    public PrPuertos() {
    }

	
    public PrPuertos(int idpuerto, String puerto, BigDecimal adicional, BigDecimal bonificacion) {
        this.idpuerto = idpuerto;
        this.puerto = puerto;
        this.adicional = adicional;
        this.bonificacion = bonificacion;
    }
    public PrPuertos(int idpuerto, String puerto, BigDecimal adicional, BigDecimal bonificacion, Integer interno, Double latitud, Double longitud, String domicilio, Set prMuelleses, Set timeshipsForIdpuertoorigen, Set timeshipsForIdpuertodestino) {
       this.idpuerto = idpuerto;
       this.puerto = puerto;
       this.adicional = adicional;
       this.bonificacion = bonificacion;
       this.interno = interno;
       this.latitud = latitud;
       this.longitud = longitud;
       this.domicilio = domicilio;
       this.prMuelleses = prMuelleses;
       this.timeshipsForIdpuertoorigen = timeshipsForIdpuertoorigen;
       this.timeshipsForIdpuertodestino = timeshipsForIdpuertodestino;
    }

    public PrPuertos( String puerto, BigDecimal adicional, BigDecimal bonificacion, Integer interno, Double latitud, Double longitud, String domicilio) {
       this.puerto = puerto;
       this.adicional = adicional;
       this.bonificacion = bonificacion;
       this.interno = interno;
       this.latitud = latitud;
       this.longitud = longitud;
       this.domicilio = domicilio;
    }
 
    
    
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.pr_puertos_idpuerto_seq")
    @Column(name="idpuerto", unique=true, nullable=false, insertable=false)
    public int getIdpuerto() {
        return this.idpuerto;
    }
    
    public void setIdpuerto(int idpuerto) {
        this.idpuerto = idpuerto;
    }

    
    @Column(name="puerto", unique=true, nullable=false, length=50)
    public String getPuerto() {
        return this.puerto;
    }
    
    public void setPuerto(String puerto) {
        this.puerto = puerto;
    }

    
    @Column(name="adicional", nullable=false, precision=18)
    public BigDecimal getAdicional() {
        return this.adicional;
    }
    
    public void setAdicional(BigDecimal adicional) {
        this.adicional = adicional;
    }

    
    @Column(name="bonificacion", nullable=false, precision=18)
    public BigDecimal getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(BigDecimal bonificacion) {
        this.bonificacion = bonificacion;
    }

    
    @Column(name="interno")
    public Integer getInterno() {
        return this.interno;
    }
    
    public void setInterno(Integer interno) {
        this.interno = interno;
    }

    
    @Column(name="latitud", precision=17, scale=17)
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", precision=17, scale=17)
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="domicilio", length=100)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prPuertos")
    public Set getPrMuelleses() {
        return this.prMuelleses;
    }
    
    public void setPrMuelleses(Set prMuelleses) {
        this.prMuelleses = prMuelleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prPracticos")
    public Set getTimeshipsForIdpuertoorigen() {
        return this.timeshipsForIdpuertoorigen;
    }
    
    public void setTimeshipsForIdpuertoorigen(Set timeshipsForIdpuertoorigen) {
        this.timeshipsForIdpuertoorigen = timeshipsForIdpuertoorigen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prPuertosByIdpuertodestino")
    public Set getTimeshipsForIdpuertodestino() {
        return this.timeshipsForIdpuertodestino;
    }
    
    public void setTimeshipsForIdpuertodestino(Set timeshipsForIdpuertodestino) {
        this.timeshipsForIdpuertodestino = timeshipsForIdpuertodestino;
    }




}


