package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timeship generated by hbm2java
 */
@Entity
@Table(name="timeship"
    ,schema="public"
)
public class Timeship  implements java.io.Serializable {


     private int idtimeship;
     private PrAgencias prAgencias;
     private PrBuques prBuques;
     private PrEmpresasCoordinacion prEmpresasCoordinacion;
     private PrMuelles prMuelles;
     private PrPracticos prPracticos;
     private PrPuertos prPuertosByIdpuertoorigen;
     private PrPuertos prPuertosByIdpuertodestino;
     private Usuarios usuariosByIdusuarioact;
     private Usuarios usuariosByIdusuarioalt;
     private Date etaRecalada;
     private Date etaZonaComun;
     private Date etaZonaRada;
     private Date fechaZarpa;
     private Integer idpracticoAsignado;
     private String observaciones;

    public Timeship() {
    }

	
    public Timeship(int idtimeship, PrAgencias prAgencias) {
        this.idtimeship = idtimeship;
        this.prAgencias = prAgencias;
    }
    public Timeship(int idtimeship, PrAgencias prAgencias, PrBuques prBuques, PrEmpresasCoordinacion prEmpresasCoordinacion, PrMuelles prMuelles, PrPracticos prPracticos, PrPuertos prPuertosByIdpuertoorigen, PrPuertos prPuertosByIdpuertodestino, Usuarios usuariosByIdusuarioact, Usuarios usuariosByIdusuarioalt, Date etaRecalada, Date etaZonaComun, Date etaZonaRada, Date fechaZarpa, Integer idpracticoAsignado, String observaciones) {
       this.idtimeship = idtimeship;
       this.prAgencias = prAgencias;
       this.prBuques = prBuques;
       this.prEmpresasCoordinacion = prEmpresasCoordinacion;
       this.prMuelles = prMuelles;
       this.prPracticos = prPracticos;
       this.prPuertosByIdpuertoorigen = prPuertosByIdpuertoorigen;
       this.prPuertosByIdpuertodestino = prPuertosByIdpuertodestino;
       this.usuariosByIdusuarioact = usuariosByIdusuarioact;
       this.usuariosByIdusuarioalt = usuariosByIdusuarioalt;
       this.etaRecalada = etaRecalada;
       this.etaZonaComun = etaZonaComun;
       this.etaZonaRada = etaZonaRada;
       this.fechaZarpa = fechaZarpa;
       this.idpracticoAsignado = idpracticoAsignado;
       this.observaciones = observaciones;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.timeship_idtimeship_seq")
    @Column(name="idtimeship", unique=true, nullable=false)
    public int getIdtimeship() {
        return this.idtimeship;
    }
    
    public void setIdtimeship(int idtimeship) {
        this.idtimeship = idtimeship;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idagencia", nullable=false)
    public PrAgencias getPrAgencias() {
        return this.prAgencias;
    }
    
    public void setPrAgencias(PrAgencias prAgencias) {
        this.prAgencias = prAgencias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbuque")
    public PrBuques getPrBuques() {
        return this.prBuques;
    }
    
    public void setPrBuques(PrBuques prBuques) {
        this.prBuques = prBuques;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idempresacoordinacion")
    public PrEmpresasCoordinacion getPrEmpresasCoordinacion() {
        return this.prEmpresasCoordinacion;
    }
    
    public void setPrEmpresasCoordinacion(PrEmpresasCoordinacion prEmpresasCoordinacion) {
        this.prEmpresasCoordinacion = prEmpresasCoordinacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmuelledestino")
    public PrMuelles getPrMuelles() {
        return this.prMuelles;
    }
    
    public void setPrMuelles(PrMuelles prMuelles) {
        this.prMuelles = prMuelles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpuertoorigen")
    public PrPracticos getPrPracticos() {
        return this.prPracticos;
    }
    
    public void setPrPracticos(PrPracticos prPracticos) {
        this.prPracticos = prPracticos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpuertoorigen", insertable=false, updatable=false)
    public PrPuertos getPrPuertosByIdpuertoorigen() {
        return this.prPuertosByIdpuertoorigen;
    }
    
    public void setPrPuertosByIdpuertoorigen(PrPuertos prPuertosByIdpuertoorigen) {
        this.prPuertosByIdpuertoorigen = prPuertosByIdpuertoorigen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpuertodestino")
    public PrPuertos getPrPuertosByIdpuertodestino() {
        return this.prPuertosByIdpuertodestino;
    }
    
    public void setPrPuertosByIdpuertodestino(PrPuertos prPuertosByIdpuertodestino) {
        this.prPuertosByIdpuertodestino = prPuertosByIdpuertodestino;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuarioact")
    public Usuarios getUsuariosByIdusuarioact() {
        return this.usuariosByIdusuarioact;
    }
    
    public void setUsuariosByIdusuarioact(Usuarios usuariosByIdusuarioact) {
        this.usuariosByIdusuarioact = usuariosByIdusuarioact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuarioalt")
    public Usuarios getUsuariosByIdusuarioalt() {
        return this.usuariosByIdusuarioalt;
    }
    
    public void setUsuariosByIdusuarioalt(Usuarios usuariosByIdusuarioalt) {
        this.usuariosByIdusuarioalt = usuariosByIdusuarioalt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="eta_recalada", length=29)
    public Date getEtaRecalada() {
        return this.etaRecalada;
    }
    
    public void setEtaRecalada(Date etaRecalada) {
        this.etaRecalada = etaRecalada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="eta_zona_comun", length=29)
    public Date getEtaZonaComun() {
        return this.etaZonaComun;
    }
    
    public void setEtaZonaComun(Date etaZonaComun) {
        this.etaZonaComun = etaZonaComun;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="eta_zona_rada", length=29)
    public Date getEtaZonaRada() {
        return this.etaZonaRada;
    }
    
    public void setEtaZonaRada(Date etaZonaRada) {
        this.etaZonaRada = etaZonaRada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_zarpa", length=29)
    public Date getFechaZarpa() {
        return this.fechaZarpa;
    }
    
    public void setFechaZarpa(Date fechaZarpa) {
        this.fechaZarpa = fechaZarpa;
    }

    
    @Column(name="idpractico_asignado")
    public Integer getIdpracticoAsignado() {
        return this.idpracticoAsignado;
    }
    
    public void setIdpracticoAsignado(Integer idpracticoAsignado) {
        this.idpracticoAsignado = idpracticoAsignado;
    }

    
    @Column(name="observaciones")
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


