package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tiposusuarios generated by hbm2java
 */
@Entity
@Table(name="tiposusuarios"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="tipousuario") 
)
public class Tiposusuarios  implements java.io.Serializable {


     private int idtipousuario;
     private String tipousuario;
     private Set usuarioses = new HashSet(0);

    public Tiposusuarios() {
    }

   public Tiposusuarios( String tipousuario) {        
        this.tipousuario = tipousuario;
   }
    
    
    public Tiposusuarios(int idtipousuario, String tipousuario) {
        this.idtipousuario = idtipousuario;
        this.tipousuario = tipousuario;
    }
    
    public Tiposusuarios(int idtipousuario, String tipousuario, Set usuarioses) {
       this.idtipousuario = idtipousuario;
       this.tipousuario = tipousuario;
       this.usuarioses = usuarioses;
    }
   
    @Id 
 
    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.tiposusuarios_idtipousuario_seq")  
     
    @Column(name="idtipousuario", unique=true, nullable=false, insertable = false)
    public int getIdtipousuario() {
        return this.idtipousuario;
    }
    
    public void setIdtipousuario(int idtipousuario) {
        this.idtipousuario = idtipousuario;
    }

    
    @Column(name="tipousuario", unique=true, nullable=false, length=50)
    public String getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposusuarios")
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


