package ar.com.syswarp.modelo;
// Generated 26/05/2020 18:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Usuarios  implements java.io.Serializable {


     private int idusuario;
     private Tiposusuarios tiposusuarios;
     private String email;
     private String clave;
     private String nombre;
     private String habilitado;
     private Set timeshipsForIdusuarioact = new HashSet(0);
     private Set timeshipsForIdusuarioalt = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idusuario, Tiposusuarios tiposusuarios, String email, String clave, String nombre, String habilitado) {
        this.idusuario = idusuario;
        this.tiposusuarios = tiposusuarios;
        this.email = email;
        this.clave = clave;
        this.nombre = nombre;
        this.habilitado = habilitado;
    }
    public Usuarios(int idusuario, Tiposusuarios tiposusuarios, String email, String clave, String nombre, String habilitado, Set timeshipsForIdusuarioact, Set timeshipsForIdusuarioalt) {
       this.idusuario = idusuario;
       this.tiposusuarios = tiposusuarios;
       this.email = email;
       this.clave = clave;
       this.nombre = nombre;
       this.habilitado = habilitado;
       this.timeshipsForIdusuarioact = timeshipsForIdusuarioact;
       this.timeshipsForIdusuarioalt = timeshipsForIdusuarioalt;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.SEQUENCE,  generator = "public.usuarios_idusuario_seq")
    @Column(name="idusuario", unique=true, nullable=false, insertable=false)
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipousuario", nullable=false)
    public Tiposusuarios getTiposusuarios() {
        return this.tiposusuarios;
    }
    
    public void setTiposusuarios(Tiposusuarios tiposusuarios) {
        this.tiposusuarios = tiposusuarios;
    }

    
    @Column(name="email", unique=true, nullable=false, length=70)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="clave", nullable=false, length=30)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="habilitado", nullable=false, length=1)
    public String getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(String habilitado) {
        this.habilitado = habilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariosByIdusuarioact")
    public Set getTimeshipsForIdusuarioact() {
        return this.timeshipsForIdusuarioact;
    }
    
    public void setTimeshipsForIdusuarioact(Set timeshipsForIdusuarioact) {
        this.timeshipsForIdusuarioact = timeshipsForIdusuarioact;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariosByIdusuarioalt")
    public Set getTimeshipsForIdusuarioalt() {
        return this.timeshipsForIdusuarioalt;
    }
    
    public void setTimeshipsForIdusuarioalt(Set timeshipsForIdusuarioalt) {
        this.timeshipsForIdusuarioalt = timeshipsForIdusuarioalt;
    }




}


